### ISSUE TITLE
FITS file names are not valid on windows systems

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#100]
file names like:
`solo_LB_stix-sci-a-name-123456_0000012345:06789-0000098765:04321_V01_98765.fits`

are not valid windows file names due to the `:`

would like to propose to replace the `:` with `f`

**Comment by nicHoch** [comment]
@samaloney i changed the split from : to f
i also did it in the fits file headers included in the test data.
do we have to reprocess some more fits files in the current archive?

**Comment by samaloney** [comment]
Hum will have to see what happen when we try and submit this to the solarorbiter archive.
