### ISSUE TITLE
finalize FITS/product timing

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#107]
FITS files and products:

should have an absolute time in the header (fits) or as property (product)

* OBT_BEG (the begin of the Observation) in SCETime
* OBT_END (the end of the Observation) in SCETime
* DATE_BEG (the begin of the Observation) in time format specified by TIMESYS (SCET|OBT ) 
* DATE_END (the end of the Observation) in time format specified by TIMESYS (SCET|OBT) 
* TIMESYS property/header will determine in what time format the OBS_... is

the time column in the data table should be all relative times (unit: s) to that reference time (OBT_BEG).

levelB and Lvel0 products will use SCETime as TIMESYS 
level1 and further on UTC as TIMESYS 

ToDO:

- [x] review OBT_BEG / DATE_BEG  / TIMESYS  in FITS reader/writer
- [x] time format of OBT in headers should be float
- [x] time format of OBT in file names will be be coarse time only (eq: `1234567890`)
- [x] time is FITS files names will use DATE_BEG/END
- [x] convert DATE_BEG/END TIMESYS  in Level1 processing step

**Comment by samaloney** [comment]
`OBT_BEG`, `OBT_END` are always in OBT/SCET format

`OBS_BEG`,  `OBS_MID`, `OBS_END` mush be in the time format specified in TIMESYS e.g `OBT` or `UTC`

This allows easy checking of the time conversion as `OBS_BEG/END` converted to OBT if necessary should match `OBT_BEG/END`

**Comment by samaloney** [comment]
So the actual header fields are `OBT_BEG`, `OBT_END` and  `DATE_BEG`, `DATE_AVG` and `DATE_END`OBT

**Comment by samaloney** [comment]
I think we have this now but would be good to check / test
