### ISSUE TITLE
Need to be able to easily override idb version from a centralised place

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#108]
@nicHoch  this was what I meant about it being difficult to override the IDB version

TODO remove before merge

_Originally posted by @samaloney in https://github.com/i4Ds/STIXCore/pull/105#discussion_r616638956_

**Comment by nicHoch** [comment]
done in https://github.com/i4Ds/STIXCore/pull/117

**Comment by samaloney** [comment]
I'm going to reopen this issue code still has to be manually edited to set the version here to use the pipeline or LBtoL1.

https://github.com/i4Ds/STIXCore/blob/90350d7d95b9b9afce4f1f4d0f5e8d30daa72310/stixcore/tmtc/packet_factory.py#L121-L123
