### ISSUE TITLE
Create or use existing ancillary data product for detailed ephemeris information

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#167]
In order to properly correct and compare data we need detailed ephemeris and aspect data (the fits file contain one data point at the average time) so proposal was to create an ancillary data product with the position and light travel time corrections etc.

**Proposal**
Aspect sol
Satellite orientation from spice
Solo pos (what frames)

**Comment by samaloney** [comment]
During the STIX co-location this topic was discussed an the following proposal was made for the high level columns:

- UTC time
- Aspect Solution (x, y offset in STIX frame [arcsec??])
- Roll angle in (Heliographic Stonyhurst or HEEQ which are the same just angular or cartesian representations)
- SOLO location in Heliographic Stonyhurst coordinates ( lat [deg], lon [deg] and rad [km])
- SOLO location in HEEQ Coordinates (x [km], y [km], z[km]

@paolomassa @grazwegian @FredSchuller have I missed anything

**Comment by FredSchuller** [comment]
@samaloney Looks good to me - although I'm not sure if we need both the angular and cartesian coordinates (I would vote for the angular).
Just a minor comment: when I need to get the roll angle, I'm using system='HGRTN', but I've just verified that this gives the same answer as 'HEEQ'.

**Comment by paolomassa** [comment]
Looks good also to me, thanks!

**Comment by samaloney** [comment]
Now create a L2 ephemeris data product.
