### ISSUE TITLE
Spectrogram files only contain one RCR value per file

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#188]
Spectrogram TM doesn't contain an RCR values per time bin so need to generate on the ground. Ideally would like to do using spectrogram file contents only but this probably won't be sufficient. Could look at HK data to find RCR state transition and then user a derivative of the count to find exact time bin in spectrogram data or if L1 data is present at max cadence could use this alternatively.

**Comment by samaloney** [comment]
So @nicHoch pointed out that a new sub header (including the rcr should be generate) should be generated at any rcr change see https://github.com/i4Ds/STIX-FSW/blob/af155d4df94a1f25e5797d4029e3dc8b109d9cbc/ASW/ASW/src/SciDataOfflineProc/SciDataReport/SciReport.c#L759 

From the ICD alone this wasn't clear so it maybe the case the RCR is just not being included in the generate fits files

**Comment by samaloney** [comment]
Yea have confirmed there can be multiple sub header with different RCR values fix is already done just testing a the moment so Spectrograms will have an rcr column in the data extension same as other BSD

**Comment by grazwegian** [comment]
That sounds just like what we need. However, I took a look at the packets on the platform for our first flare with an attenuator change and couldn't find any sub-headers corresponding to the different states: https://pub023.cs.technik.fhnw.ch/view/packet/bsd/5063 . It's possible the parser there isn't set up to process in this way either.
