### ISSUE TITLE
Spectrogram RCR not updated in TM 

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#193]
After fixing #188 and comparing the TM for data which contained multiple RCR changes CPD: 2110260001 SPEC: 2110260062 the RCR changes were not present in the spectrogram data. However in other spectrogram data RCR changes were recorded in the TM. After some inspection it seem as if all spectrogram packets have one sub-structure (NIX00403) containing 109 time samples (NIX00089) bar the last packet which can have less. If the RCR state change lasts longer then the 109 time samples it seems to be reported in the next packet but if the change is last less than 109 time samples the change is never reported.

Blue - CPD, Orange - Spec 
![rcr](https://user-images.githubusercontent.com/24570854/145024580-81c19e3d-2524-4986-8142-6ae90f38fa4f.png)

Data where RCR happened but was not reported
```
packets.get_value('NIX00403')
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
packets.get_value('NIX00401', attr='value')
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
packets.get_value('NIX00089')
array([109, 109, 109, 109, 109, 109, 109, 109, 109,  74])
```

Data where RCR was reported
```
packets.get_value('NIX00401', attr='value')
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
packets.get_value('NIX00403', attr='value')
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
packets.get_value('NIX00089', attr='value')
array([109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109,
       109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109,
       109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109,
       109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109,
       109, 109,  35])
```

**Comment by samaloney** [comment]
A follow up with AX tests seems to indicate the problem is localised to spectrogram only. The plot below shows the RCR state as reported in QL LC, Spectrograms and two CPDs one with all detector and energies one with the other which a much smaller numbers of detectors, pixel and energies to test if sub-structure boundary issue. Both CPDs agree exactly and seem inline with the QL data. 

![image (3)](https://user-images.githubusercontent.com/24570854/146363697-329b5c37-7499-472e-bb26-8481838f6969.png)

**Comment by nicHoch** [comment]
For the Record: the ax log with original time bins from FS with RCR

```
time, duration, counts, triggers, rcr_cur, rcr_prev
440439371:32768	13	0	0		0	0
440439372:52429	13	0	0		0	0
440439374:6554	13	0	0		0	0
440439375:26214	13	0	0		0	0
440439376:45875	13	0	0		0	0
440439378:0	13	0	0		0	0
440439379:19661	13	0	0		0	0
440439380:39322	5	255976	55076		0	0
440439381:6554	5	377054	81217		0	0
440439381:39322	5	376836	81073		0	0
440439382:6554	5	376897	81262		1	0
440439382:39322	5	377378	81544		1	1
440439383:6554	5	377629	81452		1	1
440439383:39322	5	376636	80837		1	1
440439384:6554	5	377553	81529		1	1
440439384:39322	5	377239	80739		1	1
440439385:6554	5	377308	81658		1	1
440439385:39322	5	377272	81393		1	1
440439386:6554	5	374915	81086		2	1
440439386:39322	5	376255	81558		2	2
440439387:6554	5	376828	81211		2	2
440439387:39322	5	376138	81432		2	2
440439388:6554	5	377018	81163		2	2
440439388:39322	5	376758	81403		2	2
440439389:6554	5	376203	81061		2	2
440439389:39322	5	75287	16290		2	2
440439390:6554	5	297765	64288		2	2
440439390:39322	5	376153	81193		2	2
440439391:6554	5	376004	80815		2	2
440439391:39322	5	376037	81309		2	2
440439392:6554	5	376712	81415		2	2
440439392:39322	5	376552	81491		2	2
440439393:6554	5	375912	80665		2	2
440439393:39322	5	376678	81534		2	2
440439394:6554	5	376140	80669		2	2
440439394:39322	5	376471	81584		2	2
440439395:6554	5	376609	81496		2	2
440439395:39322	5	376485	81299		2	2
440439396:6554	5	376279	81517		2	2
440439396:39322	5	376744	81317		2	2
440439397:6554	5	376297	81423		2	2
440439397:39322	5	377158	81091		2	2
440439398:6554	5	354300	78682		3	2
440439398:39322	5	311570	74040		3	3
440439399:6554	5	27212	6370		3	3
440439399:39322	5	281943	67138		3	3
440439400:6554	5	311404	74090		3	3
440439400:39322	5	311086	74166		3	3
440439401:6554	5	311546	74342		3	3
440439401:39322	5	311627	74513		3	3
440439402:6554	5	311502	74409		3	3
```

**Comment by samaloney** [comment]
Updated figure - the AB time are not bin centre which is what I assume cause the off set.

![stix_ax_rcr_test](https://user-images.githubusercontent.com/24570854/146543894-4936a06a-0466-4da5-bb61-bdd9328b2cbe.png)

**Comment by samaloney** [comment]
To summarise it seems the spectrogram data is treated like a stream and doesn't create sub-structures in the packets when the RCR state changes but only at packet boundaries. If the RCR state change lasts long enough or happens at the 'right' time it will be reported in the spectrogram TM but is not valid for all the times in the packet. Other sci products repost the flag to create a new sub-structure when the RCR state changes.
