### ISSUE TITLE
Aspect L2: streamline pipeline IDL interaction

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#200]
i propose the following struct as interface between the pipeline and the Aspect IDL part.

```

IDL> a =  {stx_aspect_dto, cha_diode0 :0.0, cha_diode1 : 0.0, chb_diode0 : 0.0, chb_diode1 : 0.0, time: 'UTCformat', duration : 0.1d, spice_disc_size : 0.0, y_srf : 0.0, z_srf : 0.0, calib : 0.0,  error : "text"}
IDL> help, a
** Structure STX_ASPECT_DTO, 12 tags, length=104, data length=104:
   CHA_DIODE0      FLOAT           0.0000000
   CHA_DIODE1      FLOAT           0.0000000
   CHB_DIODE0      FLOAT           0.0000000
   CHB_DIODE1      FLOAT           0.0000000
   TIME            STRING    'UTCformat'
   DURATION        FLOAT          0.10000000
   SPICE_DISC_SIZE FLOAT           0.0000000
   Y_SRF           FLOAT           0.0000000
   Z_SRF           FLOAT           0.0000000
   CALIB           FLOAT           0.0000000
   ERROR           STRING    'text'
IDL> 

```

so we will do all the spice lookup on pipeline side already.
@FredSchuller please provide feedback if you need more columns or other data types.

**Comment by FredSchuller** [comment]
@nicHoch
If I get the solar disc size for each measurement then I don't need any time data (and I don't need to do anything with SPICE kernels, which is great).

So I will get an array of such structures, right? 
Should the field "ERROR" be left blank if there is no error?

If memory / storage space is an issue, single precision is definitely enough for most values (including Y_SRF, Z_SRF).

One thing that I've just added on my side is a field to store the calibration factor: 
SAS_CALIB: 1.0
(also here single precision would be enough)
But I don't need one value per measurement, I compute one value for a full set of data (typically, 24 hours) and it would be good to store it in the header of the output FITS file.

**Comment by FredSchuller** [comment]
OK, I can return a value of SAS_CALIB for each data point, even if it stays constant.

**Comment by samaloney** [comment]
Can we close this now or still ongoing?

**Comment by FredSchuller** [comment]
We may still decide to change the structure of the interface object at some point (adding or renaming some fields), but I guess the issue can be closed on GitHub.
