### ISSUE TITLE
Minor issues with release L1 FITS files 

### ISSUE THREAD

**Issue by grazwegian** [i4Ds/STIXCore#205]
I have noticed some small issues with the current L1 FITS files. 

- [x]  1) In the Data Extension  of the L1 (Pixel data) the RCR is still recored as a string. 

e.g.
RCR             STRING    'State_0'
I had understood from the co-location that this would be changed to a numerical value.  

- [x] 2) In the Control Extension of the L4 (Spectrogram data) there is an extra keyword that contains a typo.

DECTECOR_MASKS  BYTE      Array[32]
There is also the expected  ‘DETECTOR_MASKS  BYTE      Array[32]’ present as well.

- [x] 3) For both L1 and L4 Data Extensions the COUNTS_ERR variable contains only the compression error. It would be good if the headers contained a comment making this clear.

- [x] 4) The number of energy bins included in the count arrays and the values given in the energy bin mask seem inconsistent. Possibly the ULD is also being included? Should be fixed in #217

**Comment by grazwegian** [comment]
4) The number of energy bins included in the count arrays and the values given in the energy bin mask seem inconsistent. Possibly the ULD is also being included?

IDL> help, data.counts
<Expression>    BYTE      = Array[23, 12, 32, 682]
IDL> print, total(control.ENERGY_BIN_MASK)
      22.0000
4a) The NUM_ENERGY_GROUPS variable doesn't seem to match either 
** Structure <3377a08>, 12 tags, length=44464, data length=44459, refs=1:
   TIME            ULONG              100
   TIMEDEL         ULONG              200
   RCR             STRING    'State_0'
   PIXEL_MASKS     BYTE      Array[12, 12]
   DETECTOR_MASKS  BYTE      Array[32]
   NUM_PIXEL_SETS  BYTE        12
   NUM_ENERGY_GROUPS
                   BYTE        10
   TRIGGERS        UINT      Array[16]
   TRIGGERS_ERR    FLOAT     Array[16]
   COUNTS          BYTE      Array[23, 12, 32]
   COUNTS_ERR      FLOAT     Array[23, 12, 32]

 pmm, data.NUM_ENERGY_GROUPS
% Compiled module: PMM.
      2.00000      10.0000

**Comment by samaloney** [comment]
For compressed pixel data or all products?

**Comment by samaloney** [comment]
Yes looks like an off-by-one error as the lowest E_channel has no counts

```
In [9]: hdul[2].data['counts'].sum(axis=0)
Out[9]:
array([      0,  829314, 1997191, 4658876, 2357381, 1167954,  554932,
        284476,  159977,   88915,   45811,   28793,   20560,   31741,
         27359,   26066,   47343,   67865,  962213,  220402,   41808,
         38222,   42947], dtype=uint64)
```

should be fairly straightforward to fix

**Comment by samaloney** [comment]
Yea so essentially when creating the sub array based the energy mask it was like this `counts[...,:e_max.max()+1]` so alway starting at 0 have modified so be `counts[...,e_min.min():e_max.max()+1]` will need to verify when reprocess the TM

**Comment by samaloney** [comment]
This seems to be fixed now - latest fits files on pub099

```
from astropy.io import fits
hudl = fits.open('solo_L1_stix-sci-xray-spec_20210417T153019-20210417T171825_V01_2104170001-53620.fits')
hudl[1].data['energy_bin_mask']
# array([[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
#         1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)
hudl[1].data['energy_bin_mask'].sum()
# 22
hudl[2].data['counts'].shape
# (3479, 22)

hudl[2].data['counts'].sum(axis=0)
# array([ 829314, 1997191, 4658876, 2357381, 1167954,  554932,  284476,
#         159977,   88915,   45811,   28793,   20560,   31741,   27359,
#          26066,   47343,   67865,  962213,  220402,   41808,   38222,
#          42947], dtype=uint64)
```
