### ISSUE TITLE
Some L1 HK data files have wrong number of rows

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIXCore#237]
In the latest version of the L1 HK maxi files (generated on 2022-05-27 by @samaloney), some are incomplete and some have repeated rows.
The correct number of rows should be 1350 for a normal day (= 86400 / 64). In some files, either the CONTROL table or the DATA table (or both) have less rows, although the data is available on datacenter.stix.i4ds
And in some files, the CONTROL table and / or the DATA table has more than 1350 rows, because some rows are repeated (even though column timedel pretends that each row is 64s duration).
Just as an illustration, file solo_L1_stix-hk-maxi_20220113_V01.fits is a very special case where CONTROL contains 1264 rows and DATA contains 1406 rows. By sending a query to datacenter for that day, I get 1350 packets, as expected.

@nicHoch this also means that the latest version of the L2 AUX data files that you just generated are affected by this problem: some have repeated rows, and some are incomplete.

**Comment by FredSchuller** [comment]
Here's a list of files with number of rows <> 1350 in CONTROL and/or in DATA table, for the time range 2022-01-01 to 2022-05-24. This list contains 35 files (~35% of the days under consideration) with an issue.
[problems_L1-HK_2022.txt](https://github.com/i4Ds/STIXCore/files/8897996/problems_L1-HK_2022.txt)

**Comment by FredSchuller** [comment]
And here is a similar list for the full year 2021.
[problems_L1-HK_2021.txt](https://github.com/i4Ds/STIXCore/files/8898143/problems_L1-HK_2021.txt)

**Comment by samaloney** [comment]
I've also check the with the latest fits fils and don't see the issue  HK files are incomplete and all seem correspond with spacecraft/instrument activities e.g. safemode, off, config etc.  @FredSchuller do you think this issue can be closed now?

| Name | UTC | Reason | L1 |
|------|-----|--------|----|
| solo_L0_stix-hk-maxi_0640137600_V01.fits | 2020-04-14T10:14 |  commissioning | ? |
| solo_L0_stix-hk-maxi_0643334400_V01.fits | 2020-05-21T00:00 |  * | solo_L1_stix-hk-maxi_20200521_V01.fits |
| solo_L0_stix-hk-maxi_0643507200_V01.fits | 2020-05-23T05:22 | * | solo_L1_stix-hk-maxi_20200523_V01.fits |
| solo_L0_stix-hk-maxi_0643680000_V01.fits | 2020-05-25T00:00 | * | solo_L1_stix-hk-maxi_20200525_V01.fits |
| solo_L0_stix-hk-maxi_0643766400_V01.fits | 2020-05-26T11:42 | * |solo_L1_stix-hk-maxi_20200526_V01.fits |
| solo_L0_stix-hk-maxi_0644371200_V01.fits | 2020-06-02T00:01 | * |solo_L1_stix-hk-maxi_20200602_V01.fits |
| solo_L0_stix-hk-maxi_0644457600_V01.fits | 2020-06-03T04:57 | * |solo_L1_stix-hk-maxi_20200603_V01.fits |
| solo_L0_stix-hk-maxi_0647308800_V01.fits | 2020-07-06T00:00 | * |solo_L1_stix-hk-maxi_20200706_V01.fits |
| solo_L0_stix-hk-maxi_0647913600_V01.fits | 2020-07-13T11:08 | * |solo_L1_stix-hk-maxi_20200713_V01.fits |
| solo_L0_stix-hk-maxi_0651283200_V01.fits | 2020-08-21T13:38 | ? |solo_L1_stix-hk-maxi_20200821_V01.fits |
| solo_L0_stix-hk-maxi_0652665600_V01.fits | 2020-09-06T00:01 | ?  |solo_L1_stix-hk-maxi_20200906_V01.fits |
| solo_L0_stix-hk-maxi_0653356800_V01.fits | 2020-09-14T00:13 | ? |solo_L1_stix-hk-maxi_20200914_V01.fits |
| solo_L0_stix-hk-maxi_0655171200_V01.fits | 2020-10-05T00:01 | ? |solo_L1_stix-hk-maxi_20201005_V01.fits |
| solo_L0_stix-hk-maxi_0655257600_V01.fits | 2020-10-06T11:38 | ? |solo_L1_stix-hk-maxi_20201006_V01.fits |
| solo_L0_stix-hk-maxi_0657590400_V01.fits | 2020-11-02T00:01 | Off |solo_L1_stix-hk-maxi_20201102_V01.fits |
| solo_L0_stix-hk-maxi_0657849600_V01.fits | 2020-11-05T04:23 | Reboot |solo_L1_stix-hk-maxi_20201105_V01.fits |
| solo_L0_stix-hk-maxi_0659923200_V01.fits | 2020-11-29T00:01 | Safe |solo_L1_stix-hk-maxi_20201129_V01.fits |
| solo_L0_stix-hk-maxi_0660009600_V01.fits | 2020-11-30T00:13 | * |solo_L1_stix-hk-maxi_20201130_V01.fits |
| solo_L0_stix-hk-maxi_0660528000_V01.fits | 2020-12-06T00:01 | Safe |solo_L1_stix-hk-maxi_20201206_V01.fits |
| solo_L0_stix-hk-maxi_0662774400_V01.fits | 2021-01-01T00:10 | Reboot |solo_L1_stix-hk-maxi_20210101_V01.fits |
| solo_L0_stix-hk-maxi_0663120000_V01.fits | 2021-01-05T12:52 | Reboot|solo_L1_stix-hk-maxi_20210105_V01.fits |
| solo_L0_stix-hk-maxi_0664156800_V01.fits | 2021-01-17T00:01 |  Off |solo_L1_stix-hk-maxi_20210117_V01.fits |
| solo_L0_stix-hk-maxi_0664761600_V01.fits | 2021-01-24T21:29 | Reboot  |solo_L1_stix-hk-maxi_20210124_V01.fits |
| solo_L0_stix-hk-maxi_0672105600_V01.fits | 2021-04-19T00:01 | Safe |solo_L1_stix-hk-maxi_20210419_V01.fits |
| solo_L0_stix-hk-maxi_0672278400_V01.fits | 2021-04-21T17:27 | Reboot |solo_L1_stix-hk-maxi_20210421_V01.fits |
| solo_L0_stix-hk-maxi_0681696000_V01.fits | 2021-08-08T00:01 | Restart |solo_L1_stix-hk-maxi_20210623_V01.fits |
| solo_L0_stix-hk-maxi_0681782400_V01.fits | 2021-08-09T12:08 | * |solo_L1_stix-hk-maxi_20210808_V01.fits |
| solo_L0_stix-hk-maxi_0684979200_V01.fits | 2021-09-15T00:01 | Safe |solo_L1_stix-hk-maxi_20210809_V01.fits |
| solo_L0_stix-hk-maxi_0685411200_V01.fits | 2021-09-20T18:12 | Restart |solo_L1_stix-hk-maxi_20210920_V01.fits |
| solo_L0_stix-hk-maxi_0690681600_V01.fits | 2021-11-20T00:02 | Restart |solo_L1_stix-hk-maxi_20211120_V01.fits |
| solo_L0_stix-hk-maxi_0690768000_V01.fits | 2021-11-21T09:38 | * |solo_L1_stix-hk-maxi_20211121_V01.fits |
| solo_L0_stix-hk-maxi_0691027200_V01.fits | 2021-11-24T00:02 | Restart | ? |
| solo_L0_stix-hk-maxi_0692668800_V01.fits | 2021-12-13T00:02 | Safe | solo_L1_stix-hk-maxi_20211213_V01.fits |
| solo_L0_stix-hk-maxi_0692755200_V01.fits | 2021-12-14T06:48 | * | solo_L1_stix-hk-maxi_20211214_V01.fits |
| solo_L0_stix-hk-maxi_0695001600_V01.fits | 2022-01-09T00:01 | Safe | solo_L1_stix-hk-maxi_20220109_V01.fits |
| solo_L0_stix-hk-maxi_0695260800_V01.fits | 2022-01-12T04:09 | * | solo_L1_stix-hk-maxi_20220112_V01.fits |
| solo_L0_stix-hk-maxi_0703728000_V01.fits | 2022-04-20T00:02 | Off? | solo_L1_stix-hk-maxi_20220420_V01.fits |
| solo_L0_stix-hk-maxi_0704505600_V01.fits | 2022-04-29T12:26 | *  | solo_L1_stix-hk-maxi_20220429_V01.fits |
| solo_L0_stix-hk-maxi_0707788800_V01.fits | 2022-06-06T00:03 | Restart | solo_L1_stix-hk-maxi_20220606_V01.fits |
| solo_L0_stix-hk-maxi_0710121600_V01.fits | 2022-07-03T00:03 | Safe | solo_L1_stix-hk-maxi_20220703_V01.fits |
| solo_L0_stix-hk-maxi_0710208000_V01.fits | 2022-07-04T18:11 | * | solo_L1_stix-hk-maxi_20220704_V01.fits |
| solo_L0_stix-hk-maxi_0715478400_V01.fits | 2022-09-03T00:02 | Safe | solo_L1_stix-hk-maxi_20220903_V01.fits |
| solo_L0_stix-hk-maxi_0715564800_V01.fits | 2022-09-04T04:13 | * | solo_L1_stix-hk-maxi_20220904_V01.fits |
| solo_L0_stix-hk-maxi_0720748800_V01.fits | 2022-11-03T00:02 | Off ? | solo_L1_stix-hk-maxi_20221103_V01.fits |
| solo_L0_stix-hk-maxi_0721180800_V01.fits | 2022-11-08T17:46 | * | solo_L1_stix-hk-maxi_20221108_V01.fits |
| solo_L0_stix-hk-maxi_0727142400_V01.fits | 2023-01-16T00:03 | Safe | solo_L1_stix-hk-maxi_20230116_V01.fits |
| solo_L0_stix-hk-maxi_0727228800_V01.fits | 2023-01-17T00:28 | * | solo_L1_stix-hk-maxi_20230117_V01.fits |
| solo_L0_stix-hk-maxi_0727315200_V01.fits | 2023-01-18T00:02 | Safe | solo_L1_stix-hk-maxi_20230118_V01.fits |
| solo_L0_stix-hk-maxi_0727401600_V01.fits | 2023-01-19T17:11 | * | solo_L1_stix-hk-maxi_20230119_V01.fits |

**Comment by FredSchuller** [comment]
Yes, in the latest version the number of rows is consistent with what is expected.
