### ISSUE TITLE
Spice Kernel File errors

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#242]
`The eight hundred eighth file '/hdd/data/stix/spice/kernels/ck/solo_ANC_soc-flown-att_20220612T092817-20220613T174617_V01.bc' specified by KERNELS_TO_LOAD in the file /data/stix/spice/kernels/mk/solo_ANC_soc-flown-mk_V107_20220616_001.tm.abs could not be located.`

sometime the spice kernels contains errors.

Implement an option in the get_latest_mk function that dynamically finds the last working version

**Comment by samaloney** [comment]
So this was due to a problem with the transfer of files to STIX GFTS
