### ISSUE TITLE
Add addional TC packets currently only support two examples TM(1,1) and TM(21, 6) SSID=30

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#26]
I guess we should focus on the most relevant packets first? See #25 for file with example data.

- [x] HK packets  TM(3, 25) SSID 1, 2
- [x] QL data TM(21,6) SSID 30-34, 41, 43
- [x] Bulk science TM(21,6) SSID 20-24, 42
- [x] the rest

**Comment by nicHoch** [comment]
Implemented:

TM_1_1
TM_1_2
TM_1_7
TM_1_8

TM_3_25_1
TM_3_25_2

TM_5_1
TM_5_2
TM_5_3
TM_5_4

TM_6_6
TM_6_10

TM_17_2

TM_21_6_20
TM_21_6_21
TM_21_6_22
TM_21_6_23
TM_21_6_24
TM_21_6_30
TM_21_6_31
TM_21_6_32
TM_21_6_33
TM_21_6_34
TM_21_6_41
TM_21_6_42
TM_21_6_43

TM_22_2

TM_236_16
TM_236_19

TM_237_12
TM_237_20

TM_238_3
TM_238_7

TM_239_3
TM_239_6
TM_239_8
TM_239_10
TM_239_12
TM_239_14
TM_239_18
TM_239_21
