### ISSUE TITLE
Unique IDs in files are difficult to keep unique upon delivery to ESA

### ISSUE THREAD

**Issue by ennosigaeus** [i4Ds/STIXCore#260]
An issue with the IOR request generator on the platform led to IDs being reassigned (not unique anymore). This issue has been fixed, but there are still some old requests where the data has non-unique IDs. For some requests, we can quickly mitigate this as the requests cover the same data exactly. Thus, we only send one data file to ESA, possibly with an updated version tag. For other requests, an extensive list of, e.g., spectrograms share the same unique ID.

The unique ID is also added to the ESA-delivered files but stripped off. ESA has not foreseen the same product over the same time and processing level. Thus, if the STIX team requests the same event with different configurations, the resulting ESA file name will be the same for all requests, even if/when we fix the unique ID issue.

If the re-requested data are "complementary", they could be combined into a new file and the version increased. Another solution could be to append new data.

Operations can impact the technical solution to this issue. This is why we first need to collect a list of potential impact areas before technical solutions, and operational mitigation strategies can be discussed and chosen.

**Comment by ennosigaeus** [comment]
Issues to consider (please extend):
* The time in the resulting request is defined by the resulting data, not directly by the requested time frame. If two requests are made over the same time interval with different configurations, and those configurations find data at slightly different start times, the resulting start times will be different.
* Two requests could be over the exact same time, with the same detector configuration (or not), and have a different binning cadence.

**Comment by grazwegian** [comment]
Current uses where the time range and level are identical but other parameters may differ 

- Incorrect parameter (e.g. mask) applied  
    - Possible solution : provide only latest "corrected" file
- Later request with higher time cadence if more telemetry is available  
    - Possible solution : provide only later higher time cadence file
- Later cpd request with only small pixels to complement previous request with only large pixels   
    - Possible solution : combine small and large 
    - Alternative solution : provide only earlier large pixel file as it contains the vast majority of the counts
- Later spectrogram request with single rows when off-axis shadowing is likely 
    - Possible solution : provide only earlier file with all pixels summed
    - Alternative solution : provide only later file with fully illuminated row 
    - Probably depends on expected degree of shading

**Comment by ennosigaeus** [comment]
Re-requests for the same event (same or similar start and end times) may be done because:
* Change of cadence
* Change of pixel combination to be downloaded

Heuristic:
1. Sort by time
2. Remove "extra bits" (everything after the version number)
3. Select the larger or more recent file.
-> As a solution for the issues below: Later, when reprocessing the archive, we could check for a file issue, select the other file, and store it with an updated version number to allow a delivery to ESA.

There are a few potential issues:
* Could deliver two files with different contents because start and end times are slightly different.
* Could deliver only one of the two files
* Could try to deliver the latest file with the same name (and different content). Still, ESA might block it as the file has already been delivered (the question is here: is that actually good, because the two files are actually different, or should we be able to deliver - maybe with a new version number)

Way forward:
* Implement the (a) heuristic
* Execute a dry run and check the files we would deliver
* Discuss options

**Comment by samaloney** [comment]
So I spoke with Helen and Dave at the SolarOrbiter meeting and we discussed the various options essentially:
1. Just use the version field and educate users to use the free field also the software version is in the fits header not as clean as keeping software version equal to file version but not bad
2. Create some more descriptors `cpd-he`, `cpd-ht` where `he` high energy res and `ht` high time res etc.
3. Combine the extra data inside the same fits files append the HDUs (waiting on ESA to confirm if this would work with there system)

**Comment by ennosigaeus** [comment]
We discussed this and have come up with a good approach. It is recorded in the colocation notes: https://v000658.fhnw.ch/index.php/s/xstW2dysfksSE3M
