### ISSUE TITLE
Special handling for packet with incorrect times

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#283]
Some packet have time that are from the distant future due to clock sync on STIX boot - maybe put such packet in a special directory etc.

**Comment by samaloney** [comment]
So I think we should just not create L1 data for products/packets with UTC times in the future

**Comment by samaloney** [comment]
Look at reprocessing https://pub099.cs.technik.fhnw.ch/fits/L1/2025/03/14/SCI/ see if still happens

**Comment by nicHoch** [comment]
closing with #405
