### ISSUE TITLE
Mismatch between detector mask and shape of counts array in cpd files

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIXCore#291]
In some L1 pixel data files (solo_L1_stix-sci-cpd*.fits files), the shape of the counts array does not match the expected one according to the detector mask. This happens for 286 files (see list attached).
This produces an error when reading the file with procedure `stx_read_pixel_data_fits_file` in STIX-GSW.

In addition, in 14 cases also the number of energy bins doesn't match the shape of the counts array; but these are all from May 2020 (i.e. during NECP) and probably not an issue anymore.

The number of pixels according to pixel mask is very often less than 12 (in about 3,000 files), but this doesn't seem to be an issue for the file reading procedure, which always expects 12 pixels per detector, in agreement with the shape of the data array.

[stx_cpd_files_Ndet_mismatch.txt](https://github.com/i4Ds/STIXCore/files/10030684/stx_cpd_files_Ndet_mismatch.txt)

**Comment by samaloney** [comment]
So they way the software currently works only the energy dimension changes based on the request so the for compressed pixel data or l1 (not L1) the count data will always be `t x 32 x 12 x e` where `t` is the number of times and `e` is the number of requested energies.

I had a look at the requests in you file you attached and the vast majority are for either the 30 imaging detector or only the background detector we could update the software to treat detector and pixels in a similar way to energies but not sure how difficult this would be or it it worth in in terms of the amount of space we could save. In the case of single detector requests there is a lot of wasted space in the fits files as `t x 31 x 12 x e` of the `t x 32 x 12 x e` entires will be all zeros.

**Comment by samaloney** [comment]
@grazwegian @paolomassa @FredSchuller we discussed this today and decided it would be a good idea to do the above but we need to coordinate with the IDL code.

This PR makes all pixel data count dimensions vary, similarly to how the energy dimension currently works, matching the  number of requested energies. Currently all pixel data have shape `t x 32 x 12 x  e` where `t` is the number of times and `e` is the number of energies. When we reprocess the data after this change pixel data will be `t x d x p x e` where `d` is the number of detectors and `p` is the number of pixel. This save some space when we only request large pixels but a huge amount (~97%) when only BKG detector data is requested. Note the detector and pixel masks do and will continue to have sizes of 32 and 12. I think the easiest way is handle this is the when the data is read in you create the a `t x 32 x 12 x  e` and then it in from the data in the fits file the way the rest of the software can stay the same, will waste some memory but prob not huge issue.

For example if only the BKG detector was request the count dims would be `t x 1 x p x e` and the detector mask would tell you which detector/s the count belong to

See #296 for the changes to pipeline.

**Comment by paolomassa** [comment]
Hi @samaloney,

ok, thanks! When will this change in the data be effective? Just to have an idea of the time we have for making the changes in the code

**Comment by paolomassa** [comment]
@FredSchuller 
Ok thank you! Let me know if I can do anything

**Comment by grazwegian** [comment]
In the software side the data doesn't usually spend long in the full expanded form before it is converted to visiblities or spectrograms so it is indeed probably quite low priority to handle using a reduced format there as opposed to filling things into potentially mostly empty arrays.

**Comment by FredSchuller** [comment]
@samaloney I understand that this issue was fixed on the STIXcore side with pull request #296 
In order to update and test the reading side (in STIX-GSW) I would need example files generated with the fixed version, esp. in cases where it was wrong before the fix.
Do you have such new files available? Or should I wait until you re-process all the data with the new version of the pipeline?

**Comment by samaloney** [comment]
Yes we will batch process be testing and batch processing the data soon and can give you some examples files then.

**Comment by FredSchuller** [comment]
### Update on this issue
The problem was addressed with PR #296. Now the shape of counts array matches the description in pixel, detector, and energy masks in **almost all CPD files**. But the following problems still need to be solved:

- there are 136 files for data taken between Nov. 2020 and March 2021 for which two detectors were not properly configured, and the number in the detector mask (30) does not match the shape of the counts array (32). This needs to be fixed at the file generation stage
- when only one detector (e.g. BKG) was requested, on the reading side in IDL the shape of the counts array has one dimension less, although the TDIM keyword in the FITS header is correct . This will be addressed in the [STIX-GSW](https://github.com/i4Ds/STIX-GSW) side
- there are 15 files where the size of pixel mask is not in agreement with the dimension of counts array. At least in some cases that I looked at, the reason is that the pixel mask changes within the file. A proper handling of such cases also requires changes in the IDL reading procedure (to do, but low priority because very few files are affected)
- there are three files with a mismatch between energy mask (8 bins set to 1) and count array shape (dimension 32):
1. `solo_L1_stix-sci-xray-cpd_20220509T010400-20220509T010833_V01_2205091986-60673.fits`
2. `solo_L1_stix-sci-xray-cpd_20220912T070823-20220912T071528_V01_2209126204-50199.fits`
3. `solo_L1_stix-sci-xray-cpd_20220917T130244-20220917T131255_V01_2209176255-50200.fits`
Actually, in all three cases,  I was the author of the request, and I had set the value of Eunit to 2 (file 1) or to 4 (files 2 and 3) to save telemetry. In all cases, the actual data only contain 4 energy bins (which is neither 8 nor 32). To deal with such grouping of energy bins would require some changes in the structure of the FITS files (storing the energy edges of all used bins instead of a boolean mask for pre-defined energy bins). But since it's a very low number of files (and apparently I'm the only one who ever changed the value of this Eunit when submitting a data request), it's not high priority. Alternatively one could remove the possibility to change this parameter when submitting a request...

Here is how the energy bin mask looks like for files 2 and 3.

![20220917_energy-mask](https://user-images.githubusercontent.com/36623402/218076972-c22e1942-dfca-4d2f-a41f-d7da504bb9e0.png)

**Comment by FredSchuller** [comment]
Two more comments:
- the issue with varying pixel mask within a file does not prevent the IDL software to read (and process) the data
- there are more files with mismatch between masks and dimensions of counts array for the NECP period (May 2020), but since these files are not relevant for science, there is no need to fix those cases.

**Comment by FredSchuller** [comment]
@samaloney 
> So I've check the latest cpd and spec files ...

Just to make sure that we're referring to the same data products: where can I find the "latest" files?

**Comment by samaloney** [comment]
You can access them here http://pub099.cs.technik.fhnw.ch/data/testing/esa_release2/
