### ISSUE TITLE
Duplicated file name from different data request

### ISSUE THREAD

**Issue by ennosigaeus** [i4Ds/STIXCore#292]
I found this curious case in our analysis of the duplicated file names.

```
solo_L1_stix-sci-xray-spec_20220124T120004-20220124T180507_V01_2201240033-59166.fits	L1	spec	20220124T120004	20220124T180507	V01	2201240033	59166	spec_20220124T120004_20220124T180507
solo_L1_stix-sci-xray-spec_20220124T120004-20220124T180507_V01_2201249786-60605.fits	L1	spec	20220124T120004	20220124T180507	V01	2201249786	60605	spec_20220124T120004_20220124T180507
```

There are two requests "behind" those two files. 
![image](https://user-images.githubusercontent.com/649330/203956702-a728d5a8-a988-475b-acc4-d6289a11ab46.png)
![image](https://user-images.githubusercontent.com/649330/203956733-9b583964-44e7-458e-9ddc-927a2ee8ad35.png)

Request number `2201249786` is over 21900 seconds and captures data from 12 pm to 6 pm, which is in line with the file name (12 - 18). The request number `2201240033` is only over 5791 seconds and starts at roughly 3 am in the morning. This should lead to a file name indicating an interval ranging from 3 am to 4:30 am. However, the file name is the same as for the other request.

**Comment by nicHoch** [comment]
some more insights: 

with the RID 2201240033 are actually 2 RIDs "connected"

2201240033 and 2201240014

here are the IORs (@drhlxiao thanks for providing the link and a new search API https://datacenter.stix.i4ds.net/api/ior/uid/2201240033) 

### 2201240033: 

IOR https://datacenter.stix.i4ds.net/view/ior/overview/675

![image](https://user-images.githubusercontent.com/2226714/204291277-13a35f68-c83e-41df-bf4a-36baa8ee19dd.png)

it says: 
Start Time - seconds (PIX00072) = 696340696  2022-01-24T11:59:59
Tmax (PIX00078) = 219000 (21900 s)  = 6h

DataCenter:
https://datacenter.stix.i4ds.net/view/list/bsd
![image](https://user-images.githubusercontent.com/2226714/204300573-b7a3bd4f-a8bb-445c-bc7e-d8f044f93eba.png)
**this DOES NOT align with the request TC**

https://datacenter.stix.i4ds.net/view/list/fits
![image](https://user-images.githubusercontent.com/2226714/204302201-d7899e62-60ed-4bf6-a081-76c47c3c4d30.png)
**this aligns with the request TC**

https://datacenter.stix.i4ds.net/view/data-request/list
![image](https://user-images.githubusercontent.com/2226714/204305245-d3bbeb1f-3d2d-432c-8941-4d2dbbdaefe7.png)
**this DOES NOT align with the request TC** it shows the request times for RID 2201240014 instate 

STIXCore product: [solo_L1_stix-sci-xray-spec_20220124T120004-20220124T180507_V01_2201240033-59166.fits](http://pub099.cs.technik.fhnw.ch/data/fits/L1/2022/01/24/SCI/solo_L1_stix-sci-xray-spec_20220124T120004-20220124T180507_V01_2201240033-59166.fits) here 
**this aligns with the request TC**

### 2201240014:

 IOR https://datacenter.stix.i4ds.net/view/ior/overview/643

![image](https://user-images.githubusercontent.com/2226714/204292208-2fad6435-f883-4493-8394-da5f04d623e9.png)

it says: 
Start Time - seconds (PIX00072) = 696307935  2022-01-24T02:53:58
Tmax (PIX00078) = 57910 (5791 s) = 1.6h

DataCenter:
https://datacenter.stix.i4ds.net/view/list/bsd
![image](https://user-images.githubusercontent.com/2226714/204299948-2825fbe6-87ec-4d9c-a19d-9eed48a48fb6.png)
**this aligns with the request TC**

https://datacenter.stix.i4ds.net/view/list/fits
![image](https://user-images.githubusercontent.com/2226714/204303839-f93a8c6a-8192-48db-b45f-4f68b5b869ae.png)
**this aligns with the request TC** question why there are many L1A files with the same vesion @drhlxiao 

https://datacenter.stix.i4ds.net/view/data-request/list
![image](https://user-images.githubusercontent.com/2226714/204306014-9e9debdd-3ba2-45b4-a222-4d3aa7f2f67e.png)
**this aligns with the request TC**

STIXCore product: [solo_L1_stix-sci-xray-spec_20220124T025410-20220124T043046_V01_2201240014-56454.fits](http://pub099.cs.technik.fhnw.ch/data/fits/L1/2022/01/24/SCI/solo_L1_stix-sci-xray-spec_20220124T025410-20220124T043046_V01_2201240014-56454.fits) 
**this aligns with the request TC**

### 2201249786:
this is the other RID where a duplication for RID 2201240033 where detected

IOR https://datacenter.stix.i4ds.net/view/ior/overview/694

![image](https://user-images.githubusercontent.com/2226714/204294680-4506145c-2443-4c4d-b7dc-9bedfd624f1e.png)

it says:
Start Time - seconds (PIX00072) = 696340696  2022-01-24T11:59:59
Tmax (PIX00078) = 219000 (21900 s)  = 6h

DataCenter:
https://datacenter.stix.i4ds.net/view/list/bsd
![image](https://user-images.githubusercontent.com/2226714/204301309-bc00984c-8396-4983-bc72-ad489cb5b602.png)
**this aligns with the request TC**

https://datacenter.stix.i4ds.net/view/list/fits
![image](https://user-images.githubusercontent.com/2226714/204304352-dca6c69c-f950-4a78-a3c6-aefcdd850ded.png)
**this aligns with the request TC**

https://datacenter.stix.i4ds.net/view/data-request/list
![image](https://user-images.githubusercontent.com/2226714/204306596-7db8a483-6469-4327-b460-7e7edb934f96.png)
**this aligns with the request TC**

STIXCore product: [solo_L1_stix-sci-xray-spec_20220124T120004-20220124T180507_V01_2201249786-60605.fits](http://pub099.cs.technik.fhnw.ch/data/fits/L1/2022/01/24/SCI/solo_L1_stix-sci-xray-spec_20220124T120004-20220124T180507_V01_2201249786-60605.fits) 
**this aligns with the request TC**


## Conclusion
for the very same time period the Spectrogram was requested twice with different RIDs `2201240033 `and `2201249786`

at some places the datacenter is mixing up the 2 __connected__ RIDs `2201240033 `and `2201240014`
from STICCore point of view it looks sound to me

**Comment by samaloney** [comment]
@nicHoch @ennosigaeus can we close this?
