### ISSUE TITLE
SOOPNAME and other keywords are not filled in L1 files

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIXCore#305]
The keywords SOOPNAME, SOOPTYPE and TARGET are present in the FITS header of L1 SCI files, but usually they are empty (even though there was a SOOP running at the time corresponding to the data).
Some users need these keywords in order to find the data products they are looking for.

**Comment by nicHoch** [comment]
@FredSchuller 
can you please provide a sample FITS file where you miss the right soop data an ideally also provide a link to soop "sheet"/or plain data what you would expect

it is good that you spottet this now we are close to a big "reprocessing"

the soop was implemented a while ago and i think we ha never a real "soop-mission" to test again at that time - and later it droped a bit from the table

**Comment by FredSchuller** [comment]
For example that file:
http://pub099.cs.technik.fhnw.ch/fits/L1/2022/10/28/SCI/solo_L1_stix-sci-xray-cpd_20221028T195914-20221028T201447_V01_2210288211-54483.fits

Data were taken during a SOOP called: L_FULL_HRES_HCAD_Eruption-Watch

There is no easy way to find the list of SOOPs as a function of time, it's on an ESA web page for which one needs to register. But it must be available in the packets that come from ESA, since other instrument teams are able to retrieve this information and include it in their L1 data products.

**Comment by samaloney** [comment]
The most recent file we have from SOC is from Dec 1 2022

```bash
/data/stix/SOLSOC/from_soc$ ls -ltr *.json
-rw-rw-r-- 1 stixcore stixcore  1381 May  8  2020 SSTX_observation_timeline_export_M01_V04.json
-rw-rw-r-- 1 stixcore stixcore  1448 Jun  9  2020 SSTX_observation_timeline_export_M02_V02.json
-rw-rw-r-- 1 stixcore stixcore  2366 Aug 13  2020 SSTX_observation_timeline_export_M02_V03.json
-rw-rw-r-- 1 stixcore stixcore  2366 Nov  5  2020 SSTX_observation_timeline_export_M02_V04.json
-rw-rw-r-- 1 stixcore stixcore  2366 Nov 26  2020 SSTX_observation_timeline_export_M02_V05.json
-rw-rw-r-- 1 stixcore stixcore  5420 Nov 27  2020 SSTX_observation_timeline_export_M03_V04.json
-rw-rw-r-- 1 stixcore stixcore  5420 Feb 19  2021 SSTX_observation_timeline_export_M03_V05.json
-rw-rw-r-- 1 stixcore stixcore 12468 May 11  2021 SSTX_observation_timeline_export_M04_V01.json
-rw-rw-r-- 1 stixcore stixcore 12468 May 12  2021 SSTX_observation_timeline_export_M04_V02.json
-rw-rw-r-- 1 stixcore stixcore 72769 Jul 30  2021 SSTX_observation_timeline_export_M05_V01.json
-rw-rw-r-- 1 stixcore stixcore 52547 Nov 29  2021 SSTX_observation_timeline_export_M06_V01.json
-rw-rw-r-- 1 stixcore stixcore 52547 Jan 21  2022 SSTX_observation_timeline_export_M06_V02.json
-rw-rw-r-- 1 stixcore stixcore 41151 Feb 10  2022 SSTX_observation_timeline_export_M07_V01.json
-rw-rw-r-- 1 stixcore stixcore 49692 May 12  2022 SSTX_observation_timeline_export_M08_V01.json
-rw-r--r-- 1 root     root     49692 Jun  8  2022 SSTX_observation_timeline_export_M91_V01.json
-rw-r--r-- 1 root     root     49692 Jun  8  2022 SSTX_observation_timeline_export_M93_V01.json
-rw-rw-r-- 1 stixcore stixcore 26062 Aug  4 09:21 SSTX_observation_timeline_export_M09_V01.json
-rw-rw-r-- 1 stixcore stixcore 26062 Aug 10 11:29 SSTX_observation_timeline_export_M09_V02.json
-rw-rw-r-- 1 stixcore stixcore 29840 Nov 18 15:29 SSTX_observation_timeline_export_M10_V01.json
-rw-rw-r-- 1 stixcore stixcore 29840 Dec  1 13:34 SSTX_observation_timeline_export_M10_V02.json
```

**Comment by nicHoch** [comment]
processing looks fine and this is working for other times. will verify with Dan in SOOPKitchen what data should be "around"

**Comment by FredSchuller** [comment]
More SOOPs that were executed in 2022:

L_FULL_HRES_HCAD_Coronal-Dynamics (from 2022-10-08T00:00 to 2022-10-12T09:00)
R_SMALL_MRES_MCAD_AR-Long-Term (from 2022-03-31T17:45 to 2022-04-04T20:26)
R_SMALL_HRES_MCAD_Polar-Observations (from 2022-0404T16:25 to 2022-04-05T23:53)

**Comment by nicHoch** [comment]
* L_FULL_HRES_HCAD_Coronal-Dynamics (from 2022-10-08T00:00 to 2022-10-12T09:00)
in SOOP data files but with other dates: 

```
{
 "startDate"		        : "2022-03-22T00:00:00Z",
 "endDate"			: "2022-03-23T00:00:00Z",
 "encodedSoopType"	: "LF1",
 "soopInstanceId"	        : "111"
 "soopType"			: "L_FULL_HRES_HCAD_Coronal-Dynamics"
 }
```

show up "as expected" for example here:

http://pub099.cs.technik.fhnw.ch/data/fits/L1/2022/03/22/QL/solo_L1_stix-ql-lightcurve_20220322_V01.fits


* R_SMALL_MRES_MCAD_AR-Long-Term (from 2022-03-31T17:45 to 2022-04-04T20:26)

NOT in SOOP data files

* R_SMALL_HRES_MCAD_Polar-Observations (from 2022-0404T16:25 to 2022-04-05T23:53)

NOT in SOOP data files


i will check with @DanRyanIrish tomorrow

**Comment by FredSchuller** [comment]
> L_FULL_HRES_HCAD_Coronal-Dynamics (from 2022-10-08T00:00 to 2022-10-12T09:00)
> in SOOP data files but with other dates:

This must be a SOOP that was executed several times. Question is why in some cases the intormation is properly written in the keywords, in other cases it's not...

**Comment by nicHoch** [comment]
at the moment this soop (L_FULL_HRES_HCAD_Coronal-Dynamic)  was just delivered once (for one time period) to use via the SOOP data files.

**Comment by nicHoch** [comment]
implemented
