### ISSUE TITLE
Propose change *_ERR FITS labels to, e.g., *_COMP_ERR

### ISSUE THREAD

**Issue by DanRyanIrish** [i4Ds/STIXCore#309]
Data columns in the STIX FITS files labelled `*_ERR` (e.g. `COUNTS_ERR`) only include compression error.  While there are good arguments for this, it transpired that the current naming led members of the STIX team to assume that it was the total error.  This confusion is more likely among the wider community.

**Proposed solution**: Change label to `*_COMP_ERR`, e.g. `COUNTS_COMP_ERR`.

**Cons**
* Longer.

**Pros**
* Explicit.
* If users don't know what `COMP` means, this makes them more likely to read the docs/comments and realise that it is only compression error.  Currently users may unwittingly think they already know what `*_ERR` means and so are less likely to read the docs and realise their mistake.

**Comment by samaloney** [comment]
I will double check the changes is as trivial as discussed
