### ISSUE TITLE
Shape of 'counts' and 'counts_comp_err' sometimes disagree

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIXCore#330]
Yesterday I closed issue #291 after performing some checks, but now I see that in some cases, the shape of counts is not the same as counts_comp_err, for example:
```
solo_L1_stix-sci-xray-cpd_20210215T130339-20210215T132124_V01_2102150012-53010.fits
> help, data.counts
<Expression>    BYTE      = Array[15, 12, 30, 102]
> help, data.counts_comp_err
<Expression>    FLOAT     = Array[15, 12, 32, 102]
```
It may well be that only the data acquired between Nov. 2020 and March 2021 are affected, due to a misconfiguration of the detectors.

**Comment by samaloney** [comment]
I checked the generated files and worked as expected:

```
hdul = fits.open('http://pub099.cs.technik.fhnw.ch/testing/esa_release3/L1/2021/02/15/SCI/solo_L1_st
    ...: ix-sci-xray-cpd_20210215T130339-20210215T132124_V01_2102150012-53010.fits')
hdul[2].data['counts_comp_err'].shape
(102, 30, 12, 15)

hdul[2].data['counts'].shape
(102, 30, 12, 15)
```

**Comment by FredSchuller** [comment]
I also checked a few files, and I can confirm that the issue seems to be fixed.
