### ISSUE TITLE
Investigate processing BSD data immediately (no 48 hour hold)

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#346]
During the GSW meeting we discussed improving the time lag for the creation of the fits files as the platform now only supplies our L1 file. It was noted that the SPICE data for BSD will already exist as it a few weeks old at this point so we could process immediately. It only HK/QL and AUX data that require SPICE kernels from the the most recent pass

**Comment by nicHoch** [comment]
released with release 0.1.1
