### ISSUE TITLE
add project configuration 

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#35]
proposed packet: https://pypi.org/project/python-configuration/

@samaloney or are you aware of some astropy standard?

**Comment by samaloney** [comment]
I've only ever use the standard lib [configparser](https://docs.python.org/3/library/configparser.html) but that library you linked to looks interesting.

**Comment by nicHoch** [comment]
yes this would be more about project configuration like pathes URL endpoints ...
the other is more about "data configuration"
but why not combine that

**Comment by nicHoch** [comment]
a first version was added with: https://github.com/i4Ds/STIXCore/pull/130
