### ISSUE TITLE
Value of Carrington longitude is not correct

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIXCore#355]
In the FITS header, the values given for "s/c heliographic longitude" (HGLN_OBS) and "s/c Carrington longitude" (CRLN_OBS) are identical, but they should not be.
For example, on 2022-04-16, the value of HGLN_OBS was around 148 deg, but CRLN_OBS should be around 343 deg.

**Comment by samaloney** [comment]
Do you have the name of the fits file? I realise it's probably all of them but always good to check.

**Comment by FredSchuller** [comment]
The file I was now looking into is `solo_L1_stix-sci-xray-cpd_20220416T184534-20220416T191818_V01_2204166205-52793.fits`
but yes, it's a "feature" that seems to be present in all files...

**Comment by samaloney** [comment]
Ok yea I see the problem essentially the spice kernels don't implement the Carrington frame so need to do an extra transformation to get the time dependent offset from Heliographic longitude

e.g.

https://github.com/i4Ds/STIXCore/blob/6dd81930999b971ae4606fa9226deaefbe3361e1/stixcore/ephemeris/manager.py#L428-L432

and

https://github.com/i4Ds/STIXCore/blob/6dd81930999b971ae4606fa9226deaefbe3361e1/stixcore/ephemeris/manager.py#L451
