### ISSUE TITLE
Two AUX ephemeris files V01 and V01U for some days

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIXCore#374]
On the server, there are sometimes two aux-ephemeris files, for example:

  | solo_L2_stix-aux-ephemeris_20231004_V01.fits | 2023-10-25 15:14 | 383K |  
-- | -- | -- | -- | --
  | solo_L2_stix-aux-ephemeris_20231004_V01U.fits | 2023-10-27 22:06 | 383K |  

This seems to be the case for many days in October 2023. There are also days in September 2023 where only a V01U file is available, although the data should be complete by now...

**Comment by samaloney** [comment]
Can this be close @nicHoch / @FredSchuller
