### ISSUE TITLE
DATAMIN, DATAMAX and BUNIT in FITS header for each product

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#394]
```

'DATAMIN'  > 'Minimum valid physical value'
'DATAMAX' > 'Maximum valid physical value'
'BUNIT' > 'Units of physical value, after application of BSCALE, BZERO'
```

are fits header keywords used by SOAR for user filtering...
as some products have multiple data-streams we have to decide for the "most interesting one" 

so fare we only provide real values for count data
```

'DATAMIN'  =  max('counts')
'DATAMAX' = max('counts')
'BUNIT' = "counts"
```

- ql-lightcurve
- ql-background
- ql-spectra
- xray-scpd
- xray-cpd
- xray-rpd

open to decide: currently proposals
- xray-vis
- aspect-burst min/max(cha_diode0, cha_diode, chb_diode0, chb_diode1)
- ql-variance
- ql-flareflag min/max(loc_y, loc_z) unit ?
- cal-energy
- tmstatusflarelist
- hk-mini
- hk-maxi
- aux-ephemeris: min/max(y_srf, z_stf) unit km

**Comment by samaloney** [comment]
It would be really usefull to add explain, expmax for the shortest and longest exposure time too.

**Comment by nicHoch** [comment]
i added a "XPOMAX" keyword with the longest exposure time: `self.data['timedel'].as_float().max().to_value('s')`

**Comment by samaloney** [comment]
To #393 or somewhere else?
