### ISSUE TITLE
Some data in AUX ephemeris files can be wrong

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIXCore#402]
In some cases, I noticed that the values in column roll_angle_rpy in the AUX ephemeris files is not correct. This column contains three numbers (roll angle, yaw and pitch), which come from the Spice kernels. When the AUX files is generated **before** the as-flown attitude kernel is available, these numbers come from the predicted attitude and can be significantly off.

For example, in solo_L2_stix-aux-ephemeris_20240325_V02U.fits  the values of yaw reach 100'' but the true (as-flown) pointing was only at 38'' off-centre.
The same is true for 20240328.

**Comment by samaloney** [comment]
Any files with ending with `U` are not final for exactly this reason when we publish/finalise them we update the spice info and remove the `U`.

**Comment by FredSchuller** [comment]
Yes but so far these files are never updated (as far as I can see), and the one and only version available can be faulty...
This should be fixed even before the files are considered as final and ready to be published, since this info is required to generate images with correct astrometry.
We had a discussion with @nicHoch on that topic but we didn't come to a solution yet.

**Comment by nicHoch** [comment]
we only do the updates in the headers so far. We also need a update-step for this column

**Comment by samaloney** [comment]
Hum but not only this column any spice derived information

**Comment by nicHoch** [comment]
my understanding is that only the pointing information differs significant from predicted to flown all other data is around timing and this works well. Is that not the case?

**Comment by samaloney** [comment]
Yea the pointing is the _most_ different but the timing, position etc can all change so to be consistent would need to update them all I think? For example the angular size of the disk is based on the standard physical size of the sun and the distance.

**Comment by FredSchuller** [comment]
but currently the pipeline generates these AUX files as soon as new HK telemetry is available and they are never updated, right?

**Comment by nicHoch** [comment]
currently the AUX files get not updated as we still do not deliver this files to SOAR. (i got a mail from Helen we are finally close now) 
all other products will gets updated on the publish to SOAR step
and this will happen to the AUX (new ANC) files as well. BUT yes we have to think about also to update some data columns - see above (this is not implemented so far)

**Comment by samaloney** [comment]
Currently but we had process to update them when they are published them to the SOAR. But with the whole L1 vs ancillary thing we wanted to wait until that was resolved before we started to publish them.

**Comment by samaloney** [comment]
Partially addressed in #405

**Comment by nicHoch** [comment]
fixed in #405
