### ISSUE TITLE
Slow parsing performance ~800s for 130Mb of TM 

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#48]
Our parsing seems slower than I'd like it would be a a good to create some use cases and then profile the code and see where and why we are slow:
1. Parsing a large amount of TM from a MOC xml file
2. Parsing a large amount of the the same data e.g. TM_21_6_21

Also depending on the profiling if the sqlite db is the issue I think we make a minimal sqlite db and test thread based reads from files and memory and add see what issues there are it to hard to tell what the issue is with the current abstractions.

 I _think_ a lot our issues from from keep the db connection open e.g.
```python
self.conn = sqlite.connection(...)

def _execute(self, ...):
    self.con.cursor.execute(....)
    ....
```
rather than something like 
```python
self.db_uri = 'sqlite://....'

def _execute(self, ...)
    with sqlite.connection(...) as conn:
        conn.cursor.execute(....)
        ....
```

**Comment by nicHoch** [comment]
first improvement with: https://github.com/i4Ds/STIXCore/pull/56  packet header parsing without any SPICE dependency

**Comment by samaloney** [comment]
Can now process all TM to day in ~ 4 hours so that ~1.28mb/s compared to 0.16 mb/s so about 10x faster think we can close this for now.
