### ISSUE TITLE
define/implement additional raw -> engineering  calibration in the IDB

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#59]
more parameters could be calibrated with the generic IDB raw->engineering  framework 

- [x] define a  list of parameters with calibration instruction @samaloney
- [x] implement IDB injection for old packets @nicHoch 
- [x] add to IDB for future versions @ennosigaeus

**Comment by samaloney** [comment]
NIX | Conversion
------------ | -------------
NIX00269  |  NIX00269 * 0.1 [seconds]
NIX00404 | (NIX00405 + 1) * 0.1  [seconds]
NIX00405 | (NIX00405 + 1) * 0.1  [seconds]
NIX00441 | (NIX00441) * 0.1 [seconds]
NIX00122 |
NIX00123 |
NIX00124 |

**Comment by nicHoch** [comment]
@samaloney 
NIX00404 | (NIX00405 + 1) * 0.1  [seconds]

multi variant dependency have to be resolved in the specific product not in the generic idb calibration.

**Comment by samaloney** [comment]
Yea that's a typo I'm trying to pull them all out of the current code - not convinced they are correct.

**Comment by nicHoch** [comment]
@samaloney as you are already done with the level1 processing of the main packets.
do you think this list ready to go . 
So i can implement this.

**Comment by samaloney** [comment]
Should ideally add NIX00123 and NIX00124

**Comment by samaloney** [comment]
@nicHoch can we closet this now or do we need to test?

**Comment by nicHoch** [comment]
@ennosigaeus for future IDBs Versions it should defined directly defined in the IDB

**Comment by ennosigaeus** [comment]
I implemented the changes and will provide you with a new intermediate IDB version for testing. NIX00441 has been removed.

**Comment by ennosigaeus** [comment]
Hm, maybe GitHub was a little too fast. Please check first if it is DONE indeed.

**Comment by samaloney** [comment]
> @samaloney
> NIX00404 | (NIX00405 + 1) * 0.1 [seconds]
> 
> multi variant dependency have to be resolved in the specific product not in the generic idb calibration.

So in each tmtc packet definition we need to check and adapt? Possible related to #116

**Comment by samaloney** [comment]
Can this be closed @nicHoch?
