### ISSUE TITLE
carry on processing information from level to level

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#85]
each product level (fits-file) should include ancestor information (used files, versions ...)
could be added to the fits header

**Comment by samaloney** [comment]
I guess each level could add additional information
LB it would be good know which TMTC files and the packet numbers or packet number range is the file
L0 -> the LB file/s used to create it
L1 -> the L0 file/s used to create
L2 -> L1 file (should be 1to1 mapping) used to create

**Comment by nicHoch** [comment]
@samaloney what do you suggest could be a good technical solution to add this data into the fits files.
As this data might become a bit more complex as just simple strings in the header?

Current example is that i would like to store a IDB information which IDB version is uses for which time periods in the FITS file. As we need that information for L1 processing.

**Comment by samaloney** [comment]
Yea I was just thinking the fits files in the headers as another information should be coming from our parameter database or somewhere else eventually?

**Comment by samaloney** [comment]
Partially required and defined in the META data req see #138

**Comment by samaloney** [comment]
I wonder can we close this now we have the parents and raw files?

**Comment by samaloney** [comment]
With the new history and comment processing we could store the parent history file at each step? I think we should either do that or close this issue.

**Comment by nicHoch** [comment]
closing
