### ISSUE TITLE
Loop over house keeping parameters to create fits columns

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#93]
Could probably replace this and the similar block above with a loop using a modified version of the the parameters name from the IDB? Override one that need to be modified or fix in idb

_Originally posted by @samaloney in https://github.com/i4Ds/STIXCore/pull/89#discussion_r598889779_

**Comment by samaloney** [comment]
#128 does this would just need to update use the same approach for HK as well.

**Comment by nicHoch** [comment]
fixed with #156
