### ISSUE TITLE
Investigate many "Missing textual calibration info" errors

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#99]
to many "Missing textual calibration info" Errors are thrown during raw to engineering calibration

**Comment by nicHoch** [comment]
@samaloney i fixed this one. on most cases this error returned the raw number instead of the text from the IDB.
currently i am not aware of any missing information in the IDB. can you please check if you somehow expected due to the old error that you got a number instead of a string?

**Comment by samaloney** [comment]
Yea I had a few places where I had to use `get_value(... attr='value`)` but I'm not sure if we should change them back as the numbers are better for serialisation.

**Comment by nicHoch** [comment]
I think many cases are not just "1" but real strings like 

```
LIKELY_BOOT
BOOT
SAFE
MAINTENANCE
CONFIGURATION
NOMINAL
TC_TRANSITION
AUTO_NOMINAL
...
```

maybe a good candidate for Level0 numbers level1 strings. Or is there something like enumerators for fits?

**Comment by nicHoch** [comment]
fixed with: https://github.com/i4Ds/STIXCore/pull/94
